### ISSUE TITLE
Build VSM failed

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#132]
From scv-20190710.log

<pre>
20190710 07:17:45 I serviceSynthesize() {"Text":"<speak><prosody rate=\"-30%\" pitch=\"-10%\"><phoneme alphabet=\"ipa\" ph=\"ɑːpəŋ\">Āpaṃ</phoneme><break time=\"0.001s\"/> <phoneme alphabet=\"ipa\" ph=\"ɑː pə t̪o\">āpato</phoneme><break time=\"0.001s\"/> <phoneme alphabet=\"ipa\" ph=\"səɲ ʝɑː nɑː t̪ɪ;\">sañjānāti;</phoneme><break time=\"0.001s\"/></prosody></speak>","TextType":"ssml","OutputFormat":"mp3","VoiceId":"Aditi","LanguageCode":"hi-IN"}
20190710 07:17:45 WARN Error: synthesizeText(undefined) expected string or Array
    at /home/ubuntu/sc-voice/src/node/abstract-tts.js:457:32
    at Promise (/home/ubuntu/sc-voice/src/node/abstract-tts.js:459:44)
    at new Promise (<anonymous>)
    at Polly.synthesizeText (/home/ubuntu/sc-voice/src/node/abstract-tts.js:412:20)
    at /home/ubuntu/sc-voice/src/node/voice.js:239:48
    at Promise (/home/ubuntu/sc-voice/src/node/voice.js:241:43)
    at new Promise (<anonymous>)
    at Voice.speak (/home/ubuntu/sc-voice/src/node/voice.js:237:20)
    at /home/ubuntu/sc-voice/src/node/vsm-store.js:193:51
    at Promise (/home/ubuntu/sc-voice/src/node/vsm-store.js:196:41)

</pre>

**Comment by firepick1** [comment]
Fixed in v1.6.10. A sutta had a segment with no Pali.

**Comment by sabbamitta** [comment]
Process is now starting. Closing.
