### ISSUE TITLE
Ignore Chinese texts, their variants, references, translations and comments for search in Voice and scv-bilara

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#374]
#### Description

Adding Chinese texts and related files causes errors like:
```
20200703 20:16:57 WARN Error: no suttaInfo({suidRef:sa4.1/en/patton,suid:sa4.1})
    at BilaraData.loadMLDoc (/home/sabbamitta/Schreibtisch/SC-Voice/scv-bilara/src/bilara-data.js:427:23)
    at /home/sabbamitta/Schreibtisch/SC-Voice/scv-bilara/src/seeker.js:586:40
```

**Comment by sabbamitta** [comment]
Fixed in v2.3.51; now bugs occurred since.
